<?php

/**
 * This is the model base class for the table "tbl_HoaDonTraHang".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HoaDonTraHang".
 *
 * Columns in table "tbl_HoaDonTraHang" available as properties of the model,
 * followed by relations of table "tbl_HoaDonTraHang" available as properties of the model.
 *
 * @property integer $id
 * @property string $ma_chung_tu
 * @property string $ngay_lap
 * @property double $tri_gia
 * @property string $ghi_chu
 * @property string $ly_do_tra_hang
 * @property integer $nhan_vien_id
 * @property integer $khach_hang_id
 * @property integer $hoa_don_ban_id
 * @property integer $chi_nhanh_id
 *
 * @property ThongTinSanPham[] $tblThongTinSanPhams
 * @property ChiNhanh $chiNhanh
 * @property NhanVien $nhanVien
 * @property KhachHang $khachHang
 * @property HoaDonBanHang $hoaDonBan
 */
abstract class BaseHoaDonTraHang extends ThongTinSanPham {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_HoaDonTraHang';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'HoaDonTraHang|HoaDonTraHangs', $n);
	}

	public static function representingColumn() {
		return 'ma_chung_tu';
	}

	public function rules() {
		return array(
			array('nhan_vien_id, khach_hang_id, hoa_don_ban_id, chi_nhanh_id', 'required'),
			array('nhan_vien_id, khach_hang_id, hoa_don_ban_id, chi_nhanh_id', 'numerical', 'integerOnly'=>true),
			array('tri_gia', 'numerical'),
			array('ma_chung_tu', 'length', 'max'=>15),
			array('ngay_lap, ghi_chu, ly_do_tra_hang', 'safe'),
			array('ma_chung_tu, ngay_lap, tri_gia, ghi_chu, ly_do_tra_hang', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, ma_chung_tu, ngay_lap, tri_gia, ghi_chu, ly_do_tra_hang, nhan_vien_id, khach_hang_id, hoa_don_ban_id, chi_nhanh_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tblThongTinSanPhams' => array(self::MANY_MANY, 'ThongTinSanPham', 'tbl_ChiTietHoaDonTra(hoa_don_tra_id, san_pham_id)'),
			'chiNhanh' => array(self::BELONGS_TO, 'ChiNhanh', 'chi_nhanh_id'),
			'nhanVien' => array(self::BELONGS_TO, 'NhanVien', 'nhan_vien_id'),
			'khachHang' => array(self::BELONGS_TO, 'KhachHang', 'khach_hang_id'),
			'hoaDonBan' => array(self::BELONGS_TO, 'HoaDonBanHang', 'hoa_don_ban_id'),
		);
	}

	public function pivotModels() {
		return array(
			'tblThongTinSanPhams' => 'ChiTietHoaDonTra',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ma_chung_tu' => Yii::t('app', 'Ma Chung Tu'),
			'ngay_lap' => Yii::t('app', 'Ngay Lap'),
			'tri_gia' => Yii::t('app', 'Tri Gia'),
			'ghi_chu' => Yii::t('app', 'Ghi Chu'),
			'ly_do_tra_hang' => Yii::t('app', 'Ly Do Tra Hang'),
			'nhan_vien_id' => null,
			'khach_hang_id' => null,
			'hoa_don_ban_id' => null,
			'chi_nhanh_id' => null,
			'tblThongTinSanPhams' => null,
			'chiNhanh' => null,
			'nhanVien' => null,
			'khachHang' => null,
			'hoaDonBan' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ma_chung_tu', $this->ma_chung_tu, true);
		$criteria->compare('ngay_lap', $this->ngay_lap, true);
		$criteria->compare('tri_gia', $this->tri_gia);
		$criteria->compare('ghi_chu', $this->ghi_chu, true);
		$criteria->compare('ly_do_tra_hang', $this->ly_do_tra_hang, true);
		$criteria->compare('nhan_vien_id', $this->nhan_vien_id);
		$criteria->compare('khach_hang_id', $this->khach_hang_id);
		$criteria->compare('hoa_don_ban_id', $this->hoa_don_ban_id);
		$criteria->compare('chi_nhanh_id', $this->chi_nhanh_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}