<?php

/**
 * This is the model base class for the table "tbl_PhieuXuat".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PhieuXuat".
 *
 * Columns in table "tbl_PhieuXuat" available as properties of the model,
 * followed by relations of table "tbl_PhieuXuat" available as properties of the model.
 *
 * @property integer $id
 * @property integer $ma_chung_tu
 * @property string $ngay_lap
 * @property double $tri_gia
 * @property string $ghi_chu
 * @property string $chi_nhanh
 * @property integer $khach_hang
 * @property string $ly_do_xuat
 * @property integer $loai_xuat_ra
 * @property integer $nhan_vien_id
 * @property integer $chi_nhanh_nhap_id
 *
 * @property ThongTinSanPham[] $tblThongTinSanPhams
 * @property ChiNhanh $chiNhanhNhap
 * @property NhanVien $nhanVien
 */
abstract class BasePhieuXuat extends ThongTinSanPham {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_PhieuXuat';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PhieuXuat|PhieuXuats', $n);
	}

	public static function representingColumn() {
		return 'ngay_lap';
	}

	public function rules() {
		return array(
			array('ma_chung_tu, nhan_vien_id, chi_nhanh_nhap_id', 'required'),
			array('ma_chung_tu, khach_hang, loai_xuat_ra, nhan_vien_id, chi_nhanh_nhap_id', 'numerical', 'integerOnly'=>true),
			array('tri_gia', 'numerical'),
			array('chi_nhanh', 'length', 'max'=>200),
			array('ngay_lap, ghi_chu, ly_do_xuat', 'safe'),
			array('ngay_lap, tri_gia, ghi_chu, chi_nhanh, khach_hang, ly_do_xuat, loai_xuat_ra', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, ma_chung_tu, ngay_lap, tri_gia, ghi_chu, chi_nhanh, khach_hang, ly_do_xuat, loai_xuat_ra, nhan_vien_id, chi_nhanh_nhap_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tblThongTinSanPhams' => array(self::MANY_MANY, 'ThongTinSanPham', 'tbl_ChiTietPhieuXuat(phieu_xuat_id, san_pham_id)'),
			'chiNhanhNhap' => array(self::BELONGS_TO, 'ChiNhanh', 'chi_nhanh_nhap_id'),
			'nhanVien' => array(self::BELONGS_TO, 'NhanVien', 'nhan_vien_id'),
		);
	}

	public function pivotModels() {
		return array(
			'tblThongTinSanPhams' => 'ChiTietPhieuXuat',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ma_chung_tu' => Yii::t('app', 'Ma Chung Tu'),
			'ngay_lap' => Yii::t('app', 'Ngay Lap'),
			'tri_gia' => Yii::t('app', 'Tri Gia'),
			'ghi_chu' => Yii::t('app', 'Ghi Chu'),
			'chi_nhanh' => Yii::t('app', 'Chi Nhanh'),
			'khach_hang' => Yii::t('app', 'Khach Hang'),
			'ly_do_xuat' => Yii::t('app', 'Ly Do Xuat'),
			'loai_xuat_ra' => Yii::t('app', 'Loai Xuat Ra'),
			'nhan_vien_id' => null,
			'chi_nhanh_nhap_id' => null,
			'tblThongTinSanPhams' => null,
			'chiNhanhNhap' => null,
			'nhanVien' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ma_chung_tu', $this->ma_chung_tu);
		$criteria->compare('ngay_lap', $this->ngay_lap, true);
		$criteria->compare('tri_gia', $this->tri_gia);
		$criteria->compare('ghi_chu', $this->ghi_chu, true);
		$criteria->compare('chi_nhanh', $this->chi_nhanh, true);
		$criteria->compare('khach_hang', $this->khach_hang);
		$criteria->compare('ly_do_xuat', $this->ly_do_xuat, true);
		$criteria->compare('loai_xuat_ra', $this->loai_xuat_ra);
		$criteria->compare('nhan_vien_id', $this->nhan_vien_id);
		$criteria->compare('chi_nhanh_nhap_id', $this->chi_nhanh_nhap_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}