<?php

/**
 * This is the model base class for the table "tbl_ChiTietHoaDonBan".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ChiTietHoaDonBan".
 *
 * Columns in table "tbl_ChiTietHoaDonBan" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $san_pham_id
 * @property integer $hoa_don_ban_id
 * @property integer $so_luong
 * @property double $don_gia
 * @property integer $san_pham_tang_id
 *
 */
abstract class BaseChiTietHoaDonBan extends ThongTinSanPham {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_ChiTietHoaDonBan';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ChiTietHoaDonBan|ChiTietHoaDonBans', $n);
	}

	public static function representingColumn() {
		return array(
			'san_pham_id',
			'hoa_don_ban_id',
		);
	}

	public function rules() {
		return array(
			array('san_pham_id, hoa_don_ban_id', 'required'),
			array('san_pham_id, hoa_don_ban_id, so_luong, san_pham_tang_id', 'numerical', 'integerOnly'=>true),
			array('don_gia', 'numerical'),
			array('so_luong, don_gia, san_pham_tang_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('san_pham_id, hoa_don_ban_id, so_luong, don_gia, san_pham_tang_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'san_pham_id' => null,
			'hoa_don_ban_id' => null,
			'so_luong' => Yii::t('app', 'So Luong'),
			'don_gia' => Yii::t('app', 'Don Gia'),
			'san_pham_tang_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('san_pham_id', $this->san_pham_id);
		$criteria->compare('hoa_don_ban_id', $this->hoa_don_ban_id);
		$criteria->compare('so_luong', $this->so_luong);
		$criteria->compare('don_gia', $this->don_gia);
		$criteria->compare('san_pham_tang_id', $this->san_pham_tang_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}