<?php

/**
 * This is the model base class for the table "tbl_PhieuNhap".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PhieuNhap".
 *
 * Columns in table "tbl_PhieuNhap" available as properties of the model,
 * followed by relations of table "tbl_PhieuNhap" available as properties of the model.
 *
 * @property integer $id
 * @property integer $ma_chung_tu
 * @property string $ngay_lap
 * @property double $tri_gia
 * @property string $ghi_chu
 * @property string $chi_nhanh
 * @property integer $loai_nhap_vao
 * @property integer $nhan_vien_id
 * @property integer $chi_nhanh_xuat_id
 *
 * @property ThongTinSanPham[] $tblThongTinSanPhams
 * @property ChiNhanh $chiNhanhXuat
 * @property NhanVien $nhanVien
 */
abstract class BasePhieuNhap extends ThongTinSanPham {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_PhieuNhap';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PhieuNhap|PhieuNhaps', $n);
	}

	public static function representingColumn() {
		return 'ngay_lap';
	}

	public function rules() {
		return array(
			array('ma_chung_tu, nhan_vien_id, chi_nhanh_xuat_id', 'required'),
			array('ma_chung_tu, loai_nhap_vao, nhan_vien_id, chi_nhanh_xuat_id', 'numerical', 'integerOnly'=>true),
			array('tri_gia', 'numerical'),
			array('chi_nhanh', 'length', 'max'=>200),
			array('ngay_lap, ghi_chu', 'safe'),
			array('ngay_lap, tri_gia, ghi_chu, chi_nhanh, loai_nhap_vao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, ma_chung_tu, ngay_lap, tri_gia, ghi_chu, chi_nhanh, loai_nhap_vao, nhan_vien_id, chi_nhanh_xuat_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tblThongTinSanPhams' => array(self::MANY_MANY, 'ThongTinSanPham', 'tbl_ChiTietPhieuNhap(phieu_nhap_id, san_pham_id)'),
			'chiNhanhXuat' => array(self::BELONGS_TO, 'ChiNhanh', 'chi_nhanh_xuat_id'),
			'nhanVien' => array(self::BELONGS_TO, 'NhanVien', 'nhan_vien_id'),
		);
	}

	public function pivotModels() {
		return array(
			'tblThongTinSanPhams' => 'ChiTietPhieuNhap',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ma_chung_tu' => Yii::t('app', 'Ma Chung Tu'),
			'ngay_lap' => Yii::t('app', 'Ngay Lap'),
			'tri_gia' => Yii::t('app', 'Tri Gia'),
			'ghi_chu' => Yii::t('app', 'Ghi Chu'),
			'chi_nhanh' => Yii::t('app', 'Chi Nhanh'),
			'loai_nhap_vao' => Yii::t('app', 'Loai Nhap Vao'),
			'nhan_vien_id' => null,
			'chi_nhanh_xuat_id' => null,
			'tblThongTinSanPhams' => null,
			'chiNhanhXuat' => null,
			'nhanVien' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ma_chung_tu', $this->ma_chung_tu);
		$criteria->compare('ngay_lap', $this->ngay_lap, true);
		$criteria->compare('tri_gia', $this->tri_gia);
		$criteria->compare('ghi_chu', $this->ghi_chu, true);
		$criteria->compare('chi_nhanh', $this->chi_nhanh, true);
		$criteria->compare('loai_nhap_vao', $this->loai_nhap_vao);
		$criteria->compare('nhan_vien_id', $this->nhan_vien_id);
		$criteria->compare('chi_nhanh_xuat_id', $this->chi_nhanh_xuat_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}