<?php

/**
 * This is the model base class for the table "tbl_ChiTietHoaDonTang".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ChiTietHoaDonTang".
 *
 * Columns in table "tbl_ChiTietHoaDonTang" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $san_pham_tang_id
 * @property integer $hoa_don_ban_id
 * @property integer $so_luong
 *
 */
abstract class BaseChiTietHoaDonTang extends CPOSActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'tbl_ChiTietHoaDonTang';
    }

    public static function label($n = 1)
    {
        if ($n <= 1) {
            return Yii::t('viLib', 'ChiTietHoaDonTang');
        } else {
            return Yii::t('viLib', 'ChiTietHoaDonTangs');
        }
    }

    public static function representingColumn()
    {
        return array(
            'san_pham_tang_id',
            'hoa_don_ban_id',
        );
    }

    public function rules()
    {
        return array(
            array('san_pham_tang_id, hoa_don_ban_id, so_luong', 'required'),
            array('san_pham_tang_id, hoa_don_ban_id, so_luong', 'numerical', 'integerOnly' => true),
            array('san_pham_tang_id, hoa_don_ban_id, so_luong', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array();
    }

    public function pivotModels()
    {
        return array();
    }

    public function attributeLabels()
    {
        return array(
            'san_pham_tang_id' => null,
            'hoa_don_ban_id' => null,
            'so_luong' => Yii::t('app', 'So Luong'),
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('san_pham_tang_id', $this->san_pham_tang_id);
        $criteria->compare('hoa_don_ban_id', $this->hoa_don_ban_id);
        $criteria->compare('so_luong', $this->so_luong);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}