<?php

/**
 * This is the model base class for the table "tbl_LoaiSanPham".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LoaiSanPham".
 *
 * Columns in table "tbl_LoaiSanPham" available as properties of the model,
 * followed by relations of table "tbl_LoaiSanPham" available as properties of the model.
 *
 * @property integer $id
 * @property string $ma_loai
 * @property string $ten_loai
 *
 * @property SanPham[] $sanPhams
 */
abstract class BaseLoaiSanPham extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_LoaiSanPham';
	}

	public static function label($n = 1) {
        if($n <= 1 ) {
            return Yii::t('viLib', 'LoaiSanPham');
        } else {
		    return Yii::t('viLib', 'LoaiSanPhams');
        }
	}

	public static function representingColumn() {
		return 'ma_loai';
	}

	public function rules() {
		return array(
			array('ma_loai', 'required'),
			array('ma_loai', 'length', 'max'=>15),
			array('ten_loai', 'length', 'max'=>100),
			array('ten_loai', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, ma_loai, ten_loai', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'sanPhams' => array(self::HAS_MANY, 'SanPham', 'loai_san_pham_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ma_loai' => Yii::t('app', 'Ma Loai'),
			'ten_loai' => Yii::t('app', 'Ten Loai'),
			'sanPhams' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ma_loai', $this->ma_loai, true);
		$criteria->compare('ten_loai', $this->ten_loai, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}