<?php

/**
 * This is the model base class for the table "tbl_HoaDonTraHang".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HoaDonTraHang".
 *
 * Columns in table "tbl_HoaDonTraHang" available as properties of the model,
 * followed by relations of table "tbl_HoaDonTraHang" available as properties of the model.
 *
 * @property integer $id
 * @property string $ly_do_tra_hang
 * @property integer $hoa_don_ban_id
 *
 * @property SanPham[] $tblSanPhams
 * @property ChungTu $id0
 * @property HoaDonBanHang $hoaDonBan
 */
abstract class BaseHoaDonTraHang extends ChungTu {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_HoaDonTraHang';
	}

	public static function label($n = 1) {
        if($n <= 1 ) {
            return Yii::t('viLib', 'HoaDonTraHang');
        } else {
		    return Yii::t('viLib', 'HoaDonTraHangs');
        }
	}

	public static function representingColumn() {
		return 'ly_do_tra_hang';
	}

	public function rules() {
		return array(
			array('id, hoa_don_ban_id', 'required'),
			array('id, hoa_don_ban_id', 'numerical', 'integerOnly'=>true),
			array('ly_do_tra_hang', 'safe'),
			array('ly_do_tra_hang', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, ly_do_tra_hang, hoa_don_ban_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tblSanPhams' => array(self::MANY_MANY, 'SanPham', 'tbl_ChiTietHoaDonTra(hoa_don_tra_id, san_pham_id)'),
			'id0' => array(self::BELONGS_TO, 'ChungTu', 'id'),
			'hoaDonBan' => array(self::BELONGS_TO, 'HoaDonBanHang', 'hoa_don_ban_id'),
		);
	}

	public function pivotModels() {
		return array(
			'tblSanPhams' => 'ChiTietHoaDonTra',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => null,
			'ly_do_tra_hang' => Yii::t('viLib', 'Ly Do Tra Hang'),
			'hoa_don_ban_id' => null,
			'tblSanPhams' => null,
			'id0' => null,
			'hoaDonBan' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ly_do_tra_hang', $this->ly_do_tra_hang, true);
		$criteria->compare('hoa_don_ban_id', $this->hoa_don_ban_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}