<?php

/**
 * This is the model base class for the table "tbl_ChiTietPhieuNhapSanPhamTang".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ChiTietPhieuNhapSanPhamTang".
 *
 * Columns in table "tbl_ChiTietPhieuNhapSanPhamTang" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $san_pham_tang_id
 * @property integer $phieu_nhap_id
 * @property integer $so_luong
 *
 */
abstract class BaseChiTietPhieuNhapSanPhamTang extends CPOSActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_ChiTietPhieuNhapSanPhamTang';
	}

	public static function label($n = 1) {
        if($n <= 1 ) {
            return Yii::t('viLib', 'ChiTietPhieuNhapSanPhamTang');
        } else {
		    return Yii::t('viLib', 'ChiTietPhieuNhapSanPhamTangs');
        }
	}

	public static function representingColumn() {
		return array(
			'san_pham_tang_id',
			'phieu_nhap_id',
		);
	}

	public function rules() {
		return array(
			array('san_pham_tang_id, phieu_nhap_id', 'required'),
			array('san_pham_tang_id, phieu_nhap_id, so_luong', 'numerical', 'integerOnly'=>true),
			array('so_luong', 'default', 'setOnEmpty' => true, 'value' => null),
			array('san_pham_tang_id, phieu_nhap_id, so_luong', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'san_pham_tang_id' => null,
			'phieu_nhap_id' => null,
			'so_luong' => Yii::t('app', 'So Luong'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('san_pham_tang_id', $this->san_pham_tang_id);
		$criteria->compare('phieu_nhap_id', $this->phieu_nhap_id);
		$criteria->compare('so_luong', $this->so_luong);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}