<?php

/**
 * This is the model base class for the table "tbl_ChiTietPhieuXuat".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ChiTietPhieuXuat".
 *
 * Columns in table "tbl_ChiTietPhieuXuat" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $san_pham_id
 * @property integer $phieu_xuat_id
 * @property integer $so_luong
 * @property double $gia_xuat
 *
 */
abstract class BaseChiTietPhieuXuat extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_ChiTietPhieuXuat';
	}

	public static function label($n = 1) {
        if($n <= 1 ) {
            return Yii::t('viLib', 'ChiTietPhieuXuat');
        } else {
		    return Yii::t('viLib', 'ChiTietPhieuXuats');
        }
	}

	public static function representingColumn() {
		return array(
			'san_pham_id',
			'phieu_xuat_id',
		);
	}

	public function rules() {
		return array(
			array('san_pham_id, phieu_xuat_id', 'required'),
			array('san_pham_id, phieu_xuat_id, so_luong', 'numerical', 'integerOnly'=>true),
			array('gia_xuat', 'numerical'),
			array('so_luong, gia_xuat', 'default', 'setOnEmpty' => true, 'value' => null),
			array('san_pham_id, phieu_xuat_id, so_luong, gia_xuat', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'san_pham_id' => null,
			'phieu_xuat_id' => null,
			'so_luong' => Yii::t('app', 'So Luong'),
			'gia_xuat' => Yii::t('app', 'Gia Xuat'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('san_pham_id', $this->san_pham_id);
		$criteria->compare('phieu_xuat_id', $this->phieu_xuat_id);
		$criteria->compare('so_luong', $this->so_luong);
		$criteria->compare('gia_xuat', $this->gia_xuat);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}