<?php

/**
 * This is the model base class for the table "tbl_SanPhamTangChiNhanh".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SanPhamTangChiNhanh".
 *
 * Columns in table "tbl_SanPhamTangChiNhanh" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $san_pham_tang_id
 * @property integer $chi_nhanh_id
 * @property integer $so_ton
 *
 */
abstract class BaseSanPhamTangChiNhanh extends CPOSActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_SanPhamTangChiNhanh';
	}

	public static function label($n = 1) {
        if($n <= 1 ) {
            return Yii::t('viLib', 'SanPhamTangChiNhanh');
        } else {
		    return Yii::t('viLib', 'SanPhamTangChiNhanhs');
        }
	}

	public static function representingColumn() {
		return array(
			'san_pham_tang_id',
			'chi_nhanh_id',
		);
	}

	public function rules() {
		return array(
			array('chi_nhanh_id', 'required'),
			array('san_pham_tang_id, chi_nhanh_id, so_ton', 'numerical', 'integerOnly'=>true),
			array('san_pham_tang_id, so_ton', 'default', 'setOnEmpty' => true, 'value' => null),
			array('san_pham_tang_id, chi_nhanh_id, so_ton', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'san_pham_tang_id' => null,
			'chi_nhanh_id' => null,
			'so_ton' => Yii::t('viLib', 'So Ton'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('san_pham_tang_id', $this->san_pham_tang_id);
		$criteria->compare('chi_nhanh_id', $this->chi_nhanh_id);
		$criteria->compare('so_ton', $this->so_ton);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}