<?php

/**
 * This is the model base class for the table "Rights".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RightsWeight".
 *
 * Columns in table "Rights" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $itemname
 * @property integer $type
 * @property integer $weight
 *
 */
abstract class BaseRightsWeight extends CPOSActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Rights';
	}

	public static function label($n = 1) {
        if($n <= 1 ) {
            return Yii::t('viLib', 'RightsWeight');
        } else {
		    return Yii::t('viLib', 'RightsWeights');
        }
	}

	public static function representingColumn() {
		return 'itemname';
	}

	public function rules() {
		return array(
			array('itemname, type', 'required'),
			array('type, weight', 'numerical', 'integerOnly'=>true),
			array('itemname', 'length', 'max'=>64),
			array('itemname, type, weight', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'itemname' => null,
			'type' => Yii::t('app', 'Type'),
			'weight' => Yii::t('app', 'Weight'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('itemname', $this->itemname);
		$criteria->compare('type', $this->type);
		$criteria->compare('weight', $this->weight);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}