<?php

/**
 * This is the model base class for the table "tbl_NhanVien".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NhanVien".
 *
 * Columns in table "tbl_NhanVien" available as properties of the model,
 * followed by relations of table "tbl_NhanVien" available as properties of the model.
 *
 * @property integer $id
 * @property string $ma_nhan_vien
 * @property string $ho_ten
 * @property string $email
 * @property string $dien_thoai
 * @property string $dia_chi
 * @property integer $gioi_tinh
 * @property string $ngay_sinh
 * @property string $trinh_do
 * @property double $luong_co_ban
 * @property string $chuyen_mon
 * @property integer $trang_thai
 * @property string $mat_khau
 * @property string $ngay_vao_lam
 * @property string $lan_dang_nhap_cuoi
 * @property integer $loai_nhan_vien_id
 * @property integer $chi_nhanh_id
 *
 * @property ChungTu[] $chungTus
 * @property Quyen[] $tblQuyens
 * @property LoaiNhanVien $loaiNhanVien
 * @property ChiNhanh $chiNhanh
 */
abstract class BaseNhanVien extends CPOSActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_NhanVien';
	}

	public static function label($n = 1) {
        if($n <= 1 ) {
            return Yii::t('viLib', 'NhanVien');
        } else {
		    return Yii::t('viLib', 'NhanViens');
        }
	}

	public static function representingColumn() {
		return 'ma_nhan_vien';
	}

	public function rules() {
		return array(
			array('ma_nhan_vien, ho_ten, trang_thai, mat_khau, loai_nhan_vien_id, chi_nhanh_id', 'required'),
			array('gioi_tinh, trang_thai, loai_nhan_vien_id, chi_nhanh_id', 'numerical', 'integerOnly'=>true),
			array('luong_co_ban', 'numerical'),
			array('ma_nhan_vien', 'length', 'max'=>10),
			array('ho_ten, dia_chi, chuyen_mon', 'length', 'max'=>200),
			array('email, trinh_do, mat_khau', 'length', 'max'=>100),
			array('dien_thoai', 'length', 'max'=>12),
			array('ngay_sinh, ngay_vao_lam, lan_dang_nhap_cuoi', 'safe'),
			array('email, dien_thoai, dia_chi, gioi_tinh, ngay_sinh, trinh_do, luong_co_ban, chuyen_mon, ngay_vao_lam, lan_dang_nhap_cuoi', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, ma_nhan_vien, ho_ten, email, dien_thoai, dia_chi, gioi_tinh, ngay_sinh, trinh_do, luong_co_ban, chuyen_mon, trang_thai, mat_khau, ngay_vao_lam, lan_dang_nhap_cuoi, loai_nhan_vien_id, chi_nhanh_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'chungTus' => array(self::HAS_MANY, 'ChungTu', 'nhan_vien_id'),
			'tblQuyens' => array(self::MANY_MANY, 'Quyen', 'tbl_GanQuyen(nhan_vien_id, quyen_id)'),
			'loaiNhanVien' => array(self::BELONGS_TO, 'LoaiNhanVien', 'loai_nhan_vien_id'),
			'chiNhanh' => array(self::BELONGS_TO, 'ChiNhanh', 'chi_nhanh_id'),
		);
	}

	public function pivotModels() {
		return array(
			'tblQuyens' => 'GanQuyen',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ma_nhan_vien' => Yii::t('app', 'Ma Nhan Vien'),
			'ho_ten' => Yii::t('app', 'Ho Ten'),
			'email' => Yii::t('app', 'Email'),
			'dien_thoai' => Yii::t('app', 'Dien Thoai'),
			'dia_chi' => Yii::t('app', 'Dia Chi'),
			'gioi_tinh' => Yii::t('app', 'Gioi Tinh'),
			'ngay_sinh' => Yii::t('app', 'Ngay Sinh'),
			'trinh_do' => Yii::t('app', 'Trinh Do'),
			'luong_co_ban' => Yii::t('app', 'Luong Co Ban'),
			'chuyen_mon' => Yii::t('app', 'Chuyen Mon'),
			'trang_thai' => Yii::t('app', 'Trang Thai'),
			'mat_khau' => Yii::t('app', 'Mat Khau'),
			'ngay_vao_lam' => Yii::t('app', 'Ngay Vao Lam'),
			'lan_dang_nhap_cuoi' => Yii::t('app', 'Lan Dang Nhap Cuoi'),
			'loai_nhan_vien_id' => null,
			'chi_nhanh_id' => null,
			'chungTus' => null,
			'tblQuyens' => null,
			'loaiNhanVien' => null,
			'chiNhanh' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ma_nhan_vien', $this->ma_nhan_vien, true);
		$criteria->compare('ho_ten', $this->ho_ten, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('dien_thoai', $this->dien_thoai, true);
		$criteria->compare('dia_chi', $this->dia_chi, true);
		$criteria->compare('gioi_tinh', $this->gioi_tinh);
		$criteria->compare('ngay_sinh', $this->ngay_sinh, true);
		$criteria->compare('trinh_do', $this->trinh_do, true);
		$criteria->compare('luong_co_ban', $this->luong_co_ban);
		$criteria->compare('chuyen_mon', $this->chuyen_mon, true);
		$criteria->compare('trang_thai', $this->trang_thai);
		$criteria->compare('mat_khau', $this->mat_khau, true);
		$criteria->compare('ngay_vao_lam', $this->ngay_vao_lam, true);
		$criteria->compare('lan_dang_nhap_cuoi', $this->lan_dang_nhap_cuoi, true);
		$criteria->compare('loai_nhan_vien_id', $this->loai_nhan_vien_id);
		$criteria->compare('chi_nhanh_id', $this->chi_nhanh_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}