<?php

/**
 * This is the model base class for the table "tbl_KhuyenMaiChiNhanh".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "KhuyenMaiChiNhanh".
 *
 * Columns in table "tbl_KhuyenMaiChiNhanh" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $khuyen_mai_id
 * @property integer $chi_nhanh_id
 *
 */
abstract class BaseKhuyenMaiChiNhanh extends CPOSActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_KhuyenMaiChiNhanh';
	}

	public static function label($n = 1) {
        if($n <= 1 ) {
            return Yii::t('viLib', 'KhuyenMaiChiNhanh');
        } else {
		    return Yii::t('viLib', 'KhuyenMaiChiNhanhs');
        }
	}

	public static function representingColumn() {
		return array(
			'khuyen_mai_id',
			'chi_nhanh_id',
		);
	}

	public function rules() {
		return array(
			array('khuyen_mai_id, chi_nhanh_id', 'required'),
			array('khuyen_mai_id, chi_nhanh_id', 'numerical', 'integerOnly'=>true),
			array('khuyen_mai_id, chi_nhanh_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'khuyen_mai_id' => null,
			'chi_nhanh_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('khuyen_mai_id', $this->khuyen_mai_id);
		$criteria->compare('chi_nhanh_id', $this->chi_nhanh_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}