<?php

/**
 * This is the model base class for the table "tbl_CauHinh".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CauHinh".
 *
 * Columns in table "tbl_CauHinh" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $so_san_pham_tren_trang
 * @property integer $so_phan_trang
 * @property integer $bat_buoc_thong_tin_khach_hang
 * @property integer $so_luong_ton_canh_bao
 *
 */
abstract class BaseCauHinh extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_CauHinh';
	}

	public static function label($n = 1) {
        if($n <= 1 ) {
            return Yii::t('viLib', 'CauHinh');
        } else {
		    return Yii::t('viLib', 'CauHinhs');
        }
	}

	public static function representingColumn() {
		return 'so_san_pham_tren_trang';
	}

	public function rules() {
		return array(
			array('so_san_pham_tren_trang, so_phan_trang, bat_buoc_thong_tin_khach_hang, so_luong_ton_canh_bao', 'numerical', 'integerOnly'=>true),
			array('so_san_pham_tren_trang, so_phan_trang, bat_buoc_thong_tin_khach_hang, so_luong_ton_canh_bao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('so_san_pham_tren_trang, so_phan_trang, bat_buoc_thong_tin_khach_hang, so_luong_ton_canh_bao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'so_san_pham_tren_trang' => Yii::t('app', 'So San Pham Tren Trang'),
			'so_phan_trang' => Yii::t('app', 'So Phan Trang'),
			'bat_buoc_thong_tin_khach_hang' => Yii::t('app', 'Bat Buoc Thong Tin Khach Hang'),
			'so_luong_ton_canh_bao' => Yii::t('app', 'So Luong Ton Canh Bao'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('so_san_pham_tren_trang', $this->so_san_pham_tren_trang);
		$criteria->compare('so_phan_trang', $this->so_phan_trang);
		$criteria->compare('bat_buoc_thong_tin_khach_hang', $this->bat_buoc_thong_tin_khach_hang);
		$criteria->compare('so_luong_ton_canh_bao', $this->so_luong_ton_canh_bao);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}