<?php

/**
 * This is the model base class for the table "tbl_ChungTu".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ChungTu".
 *
 * Columns in table "tbl_ChungTu" available as properties of the model,
 * followed by relations of table "tbl_ChungTu" available as properties of the model.
 *
 * @property integer $id
 * @property string $ma_chung_tu
 * @property string $ngay_lap
 * @property double $tri_gia
 * @property string $ghi_chu
 * @property integer $nhan_vien_id
 * @property integer $chi_nhanh_id
 *
 * @property NhanVien $nhanVien
 * @property ChiNhanh $chiNhanh
 * @property HoaDonBanHang $hoaDonBanHang
 * @property HoaDonTraHang $hoaDonTraHang
 * @property PhieuNhap $phieuNhap
 * @property PhieuXuat $phieuXuat
 */
abstract class BaseChungTu extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_ChungTu';
	}

	public static function label($n = 1) {
        if($n <= 1 ) {
            return Yii::t('viLib', 'ChungTu');
        } else {
		    return Yii::t('viLib', 'ChungTus');
        }
	}

	public static function representingColumn() {
		return 'ma_chung_tu';
	}

	public function rules() {
		return array(
			array('ma_chung_tu, ngay_lap, tri_gia, nhan_vien_id, chi_nhanh_id', 'required'),
			array('nhan_vien_id, chi_nhanh_id', 'numerical', 'integerOnly'=>true),
			array('tri_gia', 'numerical'),
			array('ma_chung_tu', 'length', 'max'=>15),
			array('ghi_chu', 'safe'),
			array('ghi_chu', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, ma_chung_tu, ngay_lap, tri_gia, ghi_chu, nhan_vien_id, chi_nhanh_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'nhanVien' => array(self::BELONGS_TO, 'NhanVien', 'nhan_vien_id'),
			'chiNhanh' => array(self::BELONGS_TO, 'ChiNhanh', 'chi_nhanh_id'),
			'hoaDonBanHang' => array(self::HAS_ONE, 'HoaDonBanHang', 'id'),
			'hoaDonTraHang' => array(self::HAS_ONE, 'HoaDonTraHang', 'id'),
			'phieuNhap' => array(self::HAS_ONE, 'PhieuNhap', 'id'),
			'phieuXuat' => array(self::HAS_ONE, 'PhieuXuat', 'id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ma_chung_tu' => Yii::t('app', 'Ma Chung Tu'),
			'ngay_lap' => Yii::t('app', 'Ngay Lap'),
			'tri_gia' => Yii::t('app', 'Tri Gia'),
			'ghi_chu' => Yii::t('app', 'Ghi Chu'),
			'nhan_vien_id' => null,
			'chi_nhanh_id' => null,
			'nhanVien' => null,
			'chiNhanh' => null,
			'hoaDonBanHang' => null,
			'hoaDonTraHang' => null,
			'phieuNhap' => null,
			'phieuXuat' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ma_chung_tu', $this->ma_chung_tu, true);
		$criteria->compare('ngay_lap', $this->ngay_lap, true);
		$criteria->compare('tri_gia', $this->tri_gia);
		$criteria->compare('ghi_chu', $this->ghi_chu, true);
		$criteria->compare('nhan_vien_id', $this->nhan_vien_id);
		$criteria->compare('chi_nhanh_id', $this->chi_nhanh_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}