<?php

/**
 * This is the model base class for the table "tbl_KhachHang".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "KhachHang".
 *
 * Columns in table "tbl_KhachHang" available as properties of the model,
 * followed by relations of table "tbl_KhachHang" available as properties of the model.
 *
 * @property integer $id
 * @property string $ma_khach_hang
 * @property string $ho_ten
 * @property string $ngay_sinh
 * @property string $dia_chi
 * @property string $thanh_pho
 * @property string $dien_thoai
 * @property string $email
 * @property string $mo_ta
 * @property integer $diem_tich_luy
 * @property integer $loai_khach_hang_id
 *
 * @property HoaDonBanHang[] $hoaDonBanHangs
 * @property LoaiKhachHang $loaiKhachHang
 */
abstract class BaseKhachHang extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_KhachHang';
	}

	public static function label($n = 1) {
        if($n <= 1 ) {
            return Yii::t('viLib', 'KhachHang');
        } else {
		    return Yii::t('viLib', 'KhachHangs');
        }
	}

	public static function representingColumn() {
		return 'ma_khach_hang';
	}

	public function rules() {
		return array(
			array('ma_khach_hang, loai_khach_hang_id', 'required'),
			array('diem_tich_luy, loai_khach_hang_id', 'numerical', 'integerOnly'=>true),
			array('ma_khach_hang', 'length', 'max'=>10),
			array('ho_ten, dia_chi', 'length', 'max'=>200),
			array('thanh_pho, email', 'length', 'max'=>100),
			array('dien_thoai', 'length', 'max'=>15),
			array('ngay_sinh, mo_ta', 'safe'),
			array('ho_ten, ngay_sinh, dia_chi, thanh_pho, dien_thoai, email, mo_ta, diem_tich_luy', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, ma_khach_hang, ho_ten, ngay_sinh, dia_chi, thanh_pho, dien_thoai, email, mo_ta, diem_tich_luy, loai_khach_hang_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'hoaDonBanHangs' => array(self::HAS_MANY, 'HoaDonBanHang', 'khach_hang_id'),
			'loaiKhachHang' => array(self::BELONGS_TO, 'LoaiKhachHang', 'loai_khach_hang_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ma_khach_hang' => Yii::t('app', 'Ma Khach Hang'),
			'ho_ten' => Yii::t('app', 'Ho Ten'),
			'ngay_sinh' => Yii::t('app', 'Ngay Sinh'),
			'dia_chi' => Yii::t('app', 'Dia Chi'),
			'thanh_pho' => Yii::t('app', 'Thanh Pho'),
			'dien_thoai' => Yii::t('app', 'Dien Thoai'),
			'email' => Yii::t('app', 'Email'),
			'mo_ta' => Yii::t('app', 'Mo Ta'),
			'diem_tich_luy' => Yii::t('app', 'Diem Tich Luy'),
			'loai_khach_hang_id' => null,
			'hoaDonBanHangs' => null,
			'loaiKhachHang' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ma_khach_hang', $this->ma_khach_hang, true);
		$criteria->compare('ho_ten', $this->ho_ten, true);
		$criteria->compare('ngay_sinh', $this->ngay_sinh, true);
		$criteria->compare('dia_chi', $this->dia_chi, true);
		$criteria->compare('thanh_pho', $this->thanh_pho, true);
		$criteria->compare('dien_thoai', $this->dien_thoai, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('mo_ta', $this->mo_ta, true);
		$criteria->compare('diem_tich_luy', $this->diem_tich_luy);
		$criteria->compare('loai_khach_hang_id', $this->loai_khach_hang_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}