<?php

/**
 * This is the model base class for the table "tbl_NhaCungCap".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NhaCungCap".
 *
 * Columns in table "tbl_NhaCungCap" available as properties of the model,
 * followed by relations of table "tbl_NhaCungCap" available as properties of the model.
 *
 * @property integer $id
 * @property string $ma_nha_cung_cap
 * @property string $ten_nha_cung_cap
 * @property string $mo_ta
 * @property string $dien_thoai
 * @property string $email
 * @property string $fax
 * @property integer $trang_thai
 *
 * @property SanPham[] $sanPhams
 */
abstract class BaseNhaCungCap extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_NhaCungCap';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'NhaCungCap|NhaCungCaps', $n);
	}

	public static function representingColumn() {
		return 'ma_nha_cung_cap';
	}

	public function rules() {
		return array(
			array('ma_nha_cung_cap, trang_thai', 'required'),
			array('trang_thai', 'numerical', 'integerOnly'=>true),
			array('ma_nha_cung_cap, dien_thoai, fax', 'length', 'max'=>15),
			array('ten_nha_cung_cap, email', 'length', 'max'=>100),
			array('mo_ta', 'safe'),
			array('ten_nha_cung_cap, mo_ta, dien_thoai, email, fax', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, ma_nha_cung_cap, ten_nha_cung_cap, mo_ta, dien_thoai, email, fax, trang_thai', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'sanPhams' => array(self::HAS_MANY, 'SanPham', 'nha_cung_cap_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ma_nha_cung_cap' => Yii::t('app', 'Ma Nha Cung Cap'),
			'ten_nha_cung_cap' => Yii::t('app', 'Ten Nha Cung Cap'),
			'mo_ta' => Yii::t('app', 'Mo Ta'),
			'dien_thoai' => Yii::t('app', 'Dien Thoai'),
			'email' => Yii::t('app', 'Email'),
			'fax' => Yii::t('app', 'Fax'),
			'trang_thai' => Yii::t('app', 'Trang Thai'),
			'sanPhams' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ma_nha_cung_cap', $this->ma_nha_cung_cap, true);
		$criteria->compare('ten_nha_cung_cap', $this->ten_nha_cung_cap, true);
		$criteria->compare('mo_ta', $this->mo_ta, true);
		$criteria->compare('dien_thoai', $this->dien_thoai, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('fax', $this->fax, true);
		$criteria->compare('trang_thai', $this->trang_thai);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}