<?php

/**
 * This is the model base class for the table "tbl_LoaiKhachHang".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LoaiKhachHang".
 *
 * Columns in table "tbl_LoaiKhachHang" available as properties of the model,
 * followed by relations of table "tbl_LoaiKhachHang" available as properties of the model.
 *
 * @property integer $id
 * @property string $ma_loai_khach_hang
 * @property string $ten_loai
 *
 * @property KhachHang[] $khachHangs
 */
abstract class BaseLoaiKhachHang extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_LoaiKhachHang';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LoaiKhachHang|LoaiKhachHangs', $n);
	}

	public static function representingColumn() {
		return 'ma_loai_khach_hang';
	}

	public function rules() {
		return array(
			array('ma_loai_khach_hang', 'required'),
			array('ma_loai_khach_hang', 'length', 'max'=>15),
			array('ten_loai', 'length', 'max'=>100),
			array('ten_loai', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, ma_loai_khach_hang, ten_loai', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'khachHangs' => array(self::HAS_MANY, 'KhachHang', 'loai_khach_hang_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ma_loai_khach_hang' => Yii::t('app', 'Ma Loai Khach Hang'),
			'ten_loai' => Yii::t('app', 'Ten Loai'),
			'khachHangs' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ma_loai_khach_hang', $this->ma_loai_khach_hang, true);
		$criteria->compare('ten_loai', $this->ten_loai, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}