<?php

/**
 * This is the model base class for the table "tbl_SanPhamTangChiNhanh".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SanPhamTangChiNhanh".
 *
 * Columns in table "tbl_SanPhamTangChiNhanh" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $san_pham_tang_id
 * @property integer $chi_nhanh_id
 * @property double $gia_tang
 * @property string $thoi_gian_bat_dau
 * @property string $thoi_gian_ket_thuc
 * @property integer $so_ton
 *
 */
abstract class BaseSanPhamTangChiNhanh extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_SanPhamTangChiNhanh';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SanPhamTangChiNhanh|SanPhamTangChiNhanhs', $n);
	}

	public static function representingColumn() {
		return array(
			'san_pham_tang_id',
			'chi_nhanh_id',
		);
	}

	public function rules() {
		return array(
			array('san_pham_tang_id, chi_nhanh_id, gia_tang, thoi_gian_bat_dau, thoi_gian_ket_thuc, so_ton', 'required'),
			array('san_pham_tang_id, chi_nhanh_id, so_ton', 'numerical', 'integerOnly'=>true),
			array('gia_tang', 'numerical'),
			array('san_pham_tang_id, chi_nhanh_id, gia_tang, thoi_gian_bat_dau, thoi_gian_ket_thuc, so_ton', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'san_pham_tang_id' => null,
			'chi_nhanh_id' => null,
			'gia_tang' => Yii::t('app', 'Gia Tang'),
			'thoi_gian_bat_dau' => Yii::t('app', 'Thoi Gian Bat Dau'),
			'thoi_gian_ket_thuc' => Yii::t('app', 'Thoi Gian Ket Thuc'),
			'so_ton' => Yii::t('app', 'So Ton'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('san_pham_tang_id', $this->san_pham_tang_id);
		$criteria->compare('chi_nhanh_id', $this->chi_nhanh_id);
		$criteria->compare('gia_tang', $this->gia_tang);
		$criteria->compare('thoi_gian_bat_dau', $this->thoi_gian_bat_dau, true);
		$criteria->compare('thoi_gian_ket_thuc', $this->thoi_gian_ket_thuc, true);
		$criteria->compare('so_ton', $this->so_ton);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}