<?php

/**
 * This is the model base class for the table "tbl_CauHinh".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CauHinh".
 *
 * Columns in table "tbl_CauHinh" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $so_san_pham_tren_trang
 * @property integer $so_luong_ton_canh_bao
 * @property integer $so_ngay_canh_bao_sinh_nhat_khach_hang
 * @property string $email_ho_tro
 *
 */
abstract class BaseCauHinh extends CPOSActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_CauHinh';
	}

	public static function label($n = 1) {
        if($n <= 1 ) {
            return Yii::t('viLib', 'CauHinh');
        } else {
		    return Yii::t('viLib', 'CauHinhs');
        }
	}

	public static function representingColumn() {
		return 'email_ho_tro';
	}

	public function rules() {
		return array(
			array('so_san_pham_tren_trang, so_luong_ton_canh_bao, so_ngay_canh_bao_sinh_nhat_khach_hang', 'numerical', 'integerOnly'=>true),
			array('email_ho_tro', 'length', 'max'=>100),
			array('so_san_pham_tren_trang, so_luong_ton_canh_bao, so_ngay_canh_bao_sinh_nhat_khach_hang, email_ho_tro', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, so_san_pham_tren_trang, so_luong_ton_canh_bao, so_ngay_canh_bao_sinh_nhat_khach_hang, email_ho_tro', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'so_san_pham_tren_trang' => Yii::t('app', 'So San Pham Tren Trang'),
			'so_luong_ton_canh_bao' => Yii::t('app', 'So Luong Ton Canh Bao'),
			'so_ngay_canh_bao_sinh_nhat_khach_hang' => Yii::t('app', 'So Ngay Canh Bao Sinh Nhat Khach Hang'),
			'email_ho_tro' => Yii::t('app', 'Email Ho Tro'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('so_san_pham_tren_trang', $this->so_san_pham_tren_trang);
		$criteria->compare('so_luong_ton_canh_bao', $this->so_luong_ton_canh_bao);
		$criteria->compare('so_ngay_canh_bao_sinh_nhat_khach_hang', $this->so_ngay_canh_bao_sinh_nhat_khach_hang);
		$criteria->compare('email_ho_tro', $this->email_ho_tro, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}