<?php

/**
 * This is the model base class for the table "tbl_KhuVuc".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "KhuVuc".
 *
 * Columns in table "tbl_KhuVuc" available as properties of the model,
 * followed by relations of table "tbl_KhuVuc" available as properties of the model.
 *
 * @property integer $id
 * @property string $ma_khu_vuc
 * @property string $ten_khu_vuc
 * @property string $mo_ta
 *
 * @property ChiNhanh[] $chiNhanhs
 */
abstract class BaseKhuVuc extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_KhuVuc';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'KhuVuc|KhuVucs', $n);
	}

	public static function representingColumn() {
		return 'ma_khu_vuc';
	}

	public function rules() {
		return array(
			array('ma_khu_vuc', 'required'),
			array('ma_khu_vuc', 'length', 'max'=>15),
			array('ten_khu_vuc', 'length', 'max'=>100),
			array('mo_ta', 'safe'),
			array('ten_khu_vuc, mo_ta', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, ma_khu_vuc, ten_khu_vuc, mo_ta', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'chiNhanhs' => array(self::HAS_MANY, 'ChiNhanh', 'khu_vuc_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ma_khu_vuc' => Yii::t('app', 'Ma Khu Vuc'),
			'ten_khu_vuc' => Yii::t('app', 'Ten Khu Vuc'),
			'mo_ta' => Yii::t('app', 'Mo Ta'),
			'chiNhanhs' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ma_khu_vuc', $this->ma_khu_vuc, true);
		$criteria->compare('ten_khu_vuc', $this->ten_khu_vuc, true);
		$criteria->compare('mo_ta', $this->mo_ta, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}