<?php

/**
 * This is the model base class for the table "tbl_LoaiNhanVien".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LoaiNhanVien".
 *
 * Columns in table "tbl_LoaiNhanVien" available as properties of the model,
 * followed by relations of table "tbl_LoaiNhanVien" available as properties of the model.
 *
 * @property integer $id
 * @property string $ma_loai_nhan_vien
 * @property string $ten_loai
 *
 * @property NhanVien[] $nhanViens
 */
abstract class BaseLoaiNhanVien extends CPOSActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_LoaiNhanVien';
	}

	public static function label($n = 1) {
        if($n <= 1 ) {
            return Yii::t('viLib', 'Employee type');
        } else {
		    return Yii::t('viLib', 'Employees types');
        }
	}

	public static function representingColumn() {
		return 'ma_loai_nhan_vien';
	}

	public function rules() {
		return array(
			array('ma_loai_nhan_vien', 'required'),
			array('ma_loai_nhan_vien', 'length', 'max'=>15),
			array('ten_loai', 'length', 'max'=>100),
			array('ten_loai', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, ma_loai_nhan_vien, ten_loai', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'nhanViens' => array(self::HAS_MANY, 'NhanVien', 'loai_nhan_vien_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('viLib', 'ID'),
			'ma_loai_nhan_vien' => Yii::t('viLib', 'Ma Loai Nhan Vien'),
			'ten_loai' => Yii::t('viLib', 'Ten Loai'),
			'nhanViens' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ma_loai_nhan_vien', $this->ma_loai_nhan_vien, true);
		$criteria->compare('ten_loai', $this->ten_loai, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}