<?php

/**
 * This is the model base class for the table "tbl_PhieuXuat".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PhieuXuat".
 *
 * Columns in table "tbl_PhieuXuat" available as properties of the model,
 * followed by relations of table "tbl_PhieuXuat" available as properties of the model.
 *
 * @property integer $id
 * @property string $ly_do_xuat
 * @property integer $loai_xuat_ra
 * @property integer $chi_nhanh_nhap_id
 *
 * @property SanPham[] $tblSanPhams
 * @property ChiNhanh $chiNhanhNhap
 * @property ChungTu $id0
 */
abstract class BasePhieuXuat extends CPOSBaseChungTu {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_PhieuXuat';
	}

	public static function label($n = 1) {
        if($n <= 1 ) {
            return Yii::t('viLib', 'PhieuXuat');
        } else {
		    return Yii::t('viLib', 'PhieuXuats');
        }
	}

	public static function representingColumn() {
		return 'ly_do_xuat';
	}

	public function rules() {
		return array(
			array('ly_do_xuat, loai_xuat_ra, chi_nhanh_nhap_id', 'required'),
			array('id, loai_xuat_ra, chi_nhanh_nhap_id', 'numerical', 'integerOnly'=>true),
			array('id, ly_do_xuat, loai_xuat_ra, chi_nhanh_nhap_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tblSanPhams' => array(self::MANY_MANY, 'SanPham', 'tbl_ChiTietPhieuXuat(phieu_xuat_id, san_pham_id)'),
			'chiNhanhNhap' => array(self::BELONGS_TO, 'ChiNhanh', 'chi_nhanh_nhap_id'),
			'id0' => array(self::BELONGS_TO, 'ChungTu', 'id'),
		);
	}

	public function pivotModels() {
		return array(
			'tblSanPhams' => 'ChiTietPhieuXuat',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => null,
			'ly_do_xuat' => Yii::t('viLib', 'Ly Do Xuat'),
			'loai_xuat_ra' => Yii::t('viLib', 'Loai Xuat Ra'),
			'chi_nhanh_nhap_id' => null,
			'tblSanPhams' => null,
			'chiNhanhNhap' => null,
			'id0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ly_do_xuat', $this->ly_do_xuat, true);
		$criteria->compare('loai_xuat_ra', $this->loai_xuat_ra);
		$criteria->compare('chi_nhanh_nhap_id', $this->chi_nhanh_nhap_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}