<?php

/**
 * This is the model base class for the table "tbl_Quyen".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Quyen".
 *
 * Columns in table "tbl_Quyen" available as properties of the model,
 * followed by relations of table "tbl_Quyen" available as properties of the model.
 *
 * @property integer $id
 * @property string $ten_quyen
 * @property integer $loai
 * @property string $mo_ta
 * @property string $bizrule
 * @property string $tham_so
 *
 * @property NhanVien[] $tblNhanViens
 * @property PhanQuyen[] $phanQuyens
 * @property PhanQuyen[] $phanQuyens1
 */
abstract class BaseQuyen extends CPOSActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_Quyen';
	}

	public static function label($n = 1) {
        if($n <= 1 ) {
            return Yii::t('viLib', 'Quyen');
        } else {
		    return Yii::t('viLib', 'Quyens');
        }
	}

	public static function representingColumn() {
		return 'ten_quyen';
	}

	public function rules() {
		return array(
			array('loai', 'numerical', 'integerOnly'=>true),
			array('ten_quyen', 'length', 'max'=>100),
			array('mo_ta, bizrule, tham_so', 'safe'),
			array('ten_quyen, loai, mo_ta, bizrule, tham_so', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, ten_quyen, loai, mo_ta, bizrule, tham_so', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tblNhanViens' => array(self::MANY_MANY, 'NhanVien', 'tbl_GanQuyen(quyen_id, nhan_vien_id)'),
			'phanQuyens' => array(self::HAS_MANY, 'PhanQuyen', 'quyen_id'),
			'phanQuyens1' => array(self::HAS_MANY, 'PhanQuyen', 'vai_tro_id'),
		);
	}

	public function pivotModels() {
		return array(
			'tblNhanViens' => 'GanQuyen',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ten_quyen' => Yii::t('app', 'Ten Quyen'),
			'loai' => Yii::t('app', 'Loai'),
			'mo_ta' => Yii::t('app', 'Mo Ta'),
			'bizrule' => Yii::t('app', 'Bizrule'),
			'tham_so' => Yii::t('app', 'Tham So'),
			'tblNhanViens' => null,
			'phanQuyens' => null,
			'phanQuyens1' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ten_quyen', $this->ten_quyen, true);
		$criteria->compare('loai', $this->loai);
		$criteria->compare('mo_ta', $this->mo_ta, true);
		$criteria->compare('bizrule', $this->bizrule, true);
		$criteria->compare('tham_so', $this->tham_so, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}