<?php

/**
 * This is the model base class for the table "tbl_LoaiNhapXuat".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LoaiNhapXuat".
 *
 * Columns in table "tbl_LoaiNhapXuat" available as properties of the model,
 * followed by relations of table "tbl_LoaiNhapXuat" available as properties of the model.
 *
 * @property integer $id
 * @property string $ma_loai_nhap_xuat
 * @property string $ten_loai_nhap_xuat
 * @property integer $loai
 *
 * @property PhieuNhap[] $phieuNhaps
 * @property PhieuXuat[] $phieuXuats
 */
abstract class BaseLoaiNhapXuat extends CPOSActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'tbl_LoaiNhapXuat';
    }

    public static function label($n = 1)
    {
        if ($n <= 1) {
            return Yii::t('viLib', 'LoaiNhapXuat');
        } else {
            return Yii::t('viLib', 'LoaiNhapXuats');
        }
    }

    public static function representingColumn()
    {
        return 'ma_loai_nhap_xuat';
    }

    public function rules()
    {
        return array(
            array('ma_loai_nhap_xuat, ten_loai_nhap_xuat, loai', 'required'),
            array('loai', 'numerical', 'integerOnly' => true),
            array('ma_loai_nhap_xuat', 'length', 'max' => 15),
            array('ten_loai_nhap_xuat', 'length', 'max' => 100),
            array('id, ma_loai_nhap_xuat, ten_loai_nhap_xuat, loai', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'phieuNhaps' => array(self::HAS_MANY, 'PhieuNhap', 'loai_nhap_vao'),
            'phieuXuats' => array(self::HAS_MANY, 'PhieuXuat', 'loai_xuat_ra'),
        );
    }

    public function pivotModels()
    {
        return array();
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'ma_loai_nhap_xuat' => Yii::t('app', 'Ma Loai Nhap Xuat'),
            'ten_loai_nhap_xuat' => Yii::t('app', 'Ten Loai Nhap Xuat'),
            'loai' => Yii::t('app', 'Loai'),
            'phieuNhaps' => null,
            'phieuXuats' => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('ma_loai_nhap_xuat', $this->ma_loai_nhap_xuat, true);
        $criteria->compare('ten_loai_nhap_xuat', $this->ten_loai_nhap_xuat, true);
        $criteria->compare('loai', $this->loai);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}